### ISSUE TITLE
Hyperlink hover white styling is hard to see

### ISSUE THREAD

**Issue by jayqi** [emilyriederer/emilyriederer#9]
Currently, the hover styling on hyperlinks turns text white. This makes links hard to read in the body of articles when mousing over them. 

Normal:
<img src="https://user-images.githubusercontent.com/2721979/74202245-c5d5a980-4c20-11ea-9f7e-64550e0b2934.png" width="400">

Hover:
<img src="https://user-images.githubusercontent.com/2721979/74202259-cb32f400-4c20-11ea-8695-80ba4178c1fe.png" width="410">

**Comment by emilyriederer** [comment]
Thanks so much for flagging, @jayqi ! That's a really good point. I'll definite dig into the CSS and get this cleaned up.
